src/Entity/AuthToken.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use ReallySimpleJWT\Build;
use ReallySimpleJWT\Encode;
use ReallySimpleJWT\Exception\ValidateException;
use ReallySimpleJWT\Token as Tokenizer;
use ReallySimpleJWT\Validate;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Config\Definition\Exception\Exception;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AuthTokenRepository")
 */
class AuthToken
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=4096)
     */
    private $value;

    /**
     * @ORM\Column(type="date")
     */
    private $creation;

    /**
     * @ORM\Column(type="date")
     */
    private $expiration;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ip;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\AccessToken", inversedBy="authTokens")
     */
    private $AccessTokens;


    public function __construct($user)
    {
        $tokenBuilder = new Build('JWT', new Validate(), new Encode());
        $this->creation = new DateTime();
        $this->expiration = $this->creation->modify("+1year");
        $userInfos = [
            "login" => $user->getEmail(),
            "roles" => $user->getRoles(),
            "partner" => $user->getPartner()->getName(),
        ];
        try {
            $t = $tokenBuilder->setContentType('JWT')
                ->setHeaderClaim('for', strtoupper($user->getLastName()) . ' ' . ucfirst($user->getFirstName()))
                ->setSecret('kB=&ah6M@VtK^yQbf&P9xDrkvcQh_emm55y3Kq#jy=DxLy$MufnPG6vuW33Z?v$')
                ->setIssuer('API Authenticator')
                ->setJwtId(md5(uniqid('TOKEN')))
                ->setPayloadClaim('user', $userInfos)
                ->build();
        } catch (ValidateException $e) {
            die("Build error...");
        }
        $this->value = $t->getToken();
        $this->user = $user;
        $this->AccessTokens = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreation(): ?DateTimeInterface
    {
        return $this->creation;
    }

    public function setCreation(DateTimeInterface $creation): self
    {
        $this->creation = $creation;

        return $this;
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(?string $ip): self
    {
        $this->ip = $ip;

        return $this;
    }

    /**
     * @param $secret
     * @throws Exception
     * @return bool
     */
    public function isValid($secret)
    {
        if (!Tokenizer::validate($this->getValue(), $secret))
            throw new Exception('Invalid or modified token...', 000004);
        return true;
    }

    public function getExpiration(): ?DateTimeInterface
    {
        return $this->expiration;
    }

    public function setExpiration(DateTimeInterface $expiration): self
    {
        $this->expiration = $expiration;

        return $this;
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function setValue(string $value): self
    {
        $this->value = $value;

        return $this;
    }

    /**
     * @return Collection|AccessToken[]
     */
    public function getAccessTokens(): Collection
    {
        return $this->AccessTokens;
    }

    public function addAccessToken(AccessToken $accessToken): self
    {
        if (!$this->AccessTokens->contains($accessToken)) {
            $this->AccessTokens[] = $accessToken;
        }

        return $this;
    }

    public function removeAccessToken(AccessToken $accessToken): self
    {
        if ($this->AccessTokens->contains($accessToken)) {
            $this->AccessTokens->removeElement($accessToken);
        }

        return $this;
    }

}

src/Controller/Front/ActivityController.php
<?php


namespace App\Controller\Front;

use App\Repository\ActivityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ActivityController
 * @package App\Controller\Front
 * @Route("/~private/activity")
 */
class ActivityController extends AbstractController
{
    /**
     * @param ActivityRepository $repository
     * @throws \Exception
     * @return Response
     * @Route("/",name="api_front_activity")
     */
    public function activity(ActivityRepository $repository)
    {
        $methods = ['GET', 'POST', 'PUT', 'DELETE'];
        $months = ['01','02','03','04','05','06','07','08','09','10','11','12'];
        $year = (new \DateTime())->format('Y');
        $total = 0;
        foreach ($methods as $method) {
            $activities[$year][$method] = $repository->findCallsYear($this->getUser()->getPartner(), $method,"$year");
            $total = $total + $activities[$year][$method];
        }
        foreach ($months as $month) {
            $activities[$year]['months'][$month]['GET'] = $repository->findCallsMonth($this->getUser()->getPartner(),"GET","$month");
            $activities[$year]['months'][$month]['POST'] = $repository->findCallsMonth($this->getUser()->getPartner(),"POST","$month");
            $activities[$year]['months'][$month]['PUT'] = $repository->findCallsMonth($this->getUser()->getPartner(),"PUT","$month");
            $activities[$year]['months'][$month]['DELETE'] = $repository->findCallsMonth($this->getUser()->getPartner(),"DELETE","$month");
        }
        return $this->render('front/activity.html.twig', [
            'activities' => $activities,
            'totalCalls' => $total

        ]);
    }
}

src/Controller/Front/ApiFrontController.php
<?php


namespace App\Controller\Front;

use App\Helper\DataParser;
use App\Repository\PartnerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\Routing\Annotation\Route;
use \ReflectionException;

/**
 * Class ApiFrontController
 * @package App\Controller\Front
 * @Route("/~private")
 */
class ApiFrontController extends AbstractController
{
    /**
     * @Route("/",name="api_front_dash")
     * @return Response
     */
    public function dashboard()
    {
        return $this->render('front/dash.html.twig');
    }

    /**
     * @param KernelInterface $kernel
     * @return Response
     * @throws ReflectionException
     * @Route("/datas",name="api_front_data")
     */
    public function data(KernelInterface $kernel)
    {
        $parser = new DataParser($kernel);
        $controllers = $parser->getControllers();
        return $this->render('front/data.html.twig', [
            'controllers' => $controllers,
        ]);
    }
}

src/Controller/Front/UserController.php
<?php


namespace App\Controller\Front;


use App\Entity\AuthToken;
use App\Entity\User;
use App\Form\UserCreationType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * Class UserController
 * @package App\Controller\Front
 * @Route("/~private/users")
 */
class UserController extends AbstractController
{
    /**
     * @param Request $request
     * @param UserRepository $repository
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @return Response
     * @Route("/",name="api_front_user")
     */
    public function user(Request $request, UserRepository $repository, UserPasswordEncoderInterface $passwordEncoder)
    {
        $user = new User();
        $createForm = $this->createForm(UserCreationType::class, $user);
        $createForm->handleRequest($request);
        $users = $repository->findBy(['partner' => $this->getUser()->getPartner()]);
        $em = $this->getDoctrine()->getManager();
        if ($createForm->isSubmitted() && $createForm->isValid()) {
            $user->setEmail($user->getEmail());
            $user->setFirstName($user->getFirstName());
            $user->setLastName($user->getLastName());
            $user->setPartner($this->getUser()->getPartner());
            $user->setRoles(['ROLE_USER_PARTNER']);
            $user->setPassword($passwordEncoder->encodePassword($user, $user->getPassword()));
            $em->persist($user);
            $em->flush();

            $this->addFlash('notice', 'User successfully created !');
            return $this->redirectToRoute('api_front_user');
        }
        return $this->render('front/user.html.twig', [
            'users' => $users,
            'createForm' => $createForm->createView()
        ]);
    }

    /**
     * @param User $user
     * @return Response
     * @throws \Exception
     * @Route("/delete/{user}",name="api_front_user_delete")
     */
    public function deleteUser(User $user)
    {
        if ($this->isGranted('ROLE_ADMIN_PARTNER'))
            if (($this->getUser()->getPartner() !== $user->getPartner()) || ($user === $user->getPartner()->getAdmin()))
                throw new \Exception('Hmmmm... Dangerous !');
        $em = $this->getDoctrine()->getManager();
        $authRepo = $this->getDoctrine()->getRepository(AuthToken::class);
        $auth = $authRepo->findOneBy(['user' => $user]);
        $user->setAuthToken(null);
        $em->persist($user);
        $em->flush();
        $em->remove($user);
        if ($auth !== null) {
            $em->remove($auth);
        }
        $em->flush();
        $this->addFlash('notice', 'User successfully deleted !');
        return $this->json(['Success !']);
    }

}

templates/front/code/curl.html.twig
<code class="language-bash">#Send Authentication
$API_PUBLIC_KEY = "{{ app.user.authToken.value }}"; #Your API AUTH TOKEN
$API_PRIVATE_KEY = "{% for accessToken in app.user.authToken.accessTokens %}{% if (accessToken.controller == controller.name) and (accessToken.source == controller.source) %}{{ accessToken.value }}{% endif %}{% endfor %}"; #Your API ACCESS Token
curl -X {{ method.method }} \
{{ url('api_front_login') }}{{ method.endpoint[1:] }} \
-H "API-Authorization: $API_PUBLIC_KEY" \
-H "ACCESS-Authorization: $API_PRIVATE_KEY" \
-H "Content-type: application/json" \{% if method.method is same as('PUT') %}
 #JSON Array of datas you want to update
-d '{
    {% for param in method.params %}
    "{{ param.name[1:] }}":"XXX",
    {% endfor %}
}'{% endif %}</code>

templates/front/code/php.html.twig
<code class="language-php">&lt;?php
    $API_AUTH_TOKEN = "{{ app.user.authToken.value }}"; //Your API AUTH TOKENzz
    $API_ACCESS_TOKEN = "{% for accessToken in app.user.authToken.accessTokens %}{% if (accessToken.controller == controller.name) and (accessToken.source == controller.source) %}{{ accessToken.value }}{% endif %}{% endfor %}"; //Your API ACCESS Token
    {% if method.method is same as('PUT') %}
// Create map with request parameters
    $params = array (
        {% for param in method.params %}'{{ param.name[1:] }}' => 'XXX',
        {% endfor %});
    // Build Http query using params
    $query = http_build_query ($params);
    {% endif %}
    $opts = [
        'http' => [
            'method' => "{{ method.method }}",
            'header' => "API-Authorization: $API_AUTH_KEY\r\n" .
                        "ACCESS-Authorization: $API_ACCESS_KEY\r\n"{% if method.method is same as('PUT') %}.{% else %}

    {% endif %}
    {% if method.method is same as('PUT') %}

                        "Content-Length: ".strlen($query)."\r\n",
            'content' => $query
    {% endif %}
            ]
    ];
    $context = stream_context_create($opts);
    $endpoint = file_get_contents('{{ url('api_front_login') }}{{ method.endpoint[1:] }}', false, $context);

    $response = json_decode($endpoint);
?></code>

templates/front/code/response.html.twig
<code class="language-json">HTTP/1.1 200 OK
{% if method.name is same as('list') %}
{
    "{{ controller.name~'s' }}": [
        {
        "Name": "{{ controller.name }} 1"
        },
        {
        "Name": "{{ controller.name }} 2"
        }
    ]
}
    {% else %}
{
    "{{ controller.name~'s' }}": {
        "1":
        {
        "Name": "{{ controller.name }} 1"
        }
    }
}{% endif %}</code>